### PR TITLE
Output: use logging, remove garbage output by default

### LINKED ISSUE #489: Lower verbosity by default or add option to allow removing prefixed and suffixed debug output
**Is your feature request related to a problem? Please describe.**
podman-compose prints additional debug information when commands are executed, and there appears to be no way to silence it. Some tools process CLI output as-is and expect it to be in a certain format (such as JSON), but the additional output printed by podman-compose before the actual command output can break these tools.

**Describe the solution you'd like**
Perhaps lower the default verbosity to not print debug output unless `-v` or `--verbose` is passed.

**Describe alternatives you've considered**
Leaving the current behaviour the same, and adding a flag `--silent`, `--verbosity=none` or similar, to achieve the same effect.

**Additional context**
The version I'm using is 1.0.3.

Below is an example of the problem. Suppose I have some tool that wants to execute `echo hi`, and I want to wrap this in a container using Podman, I override the command to be:

```
podman exec --interactive --tty some_container_1 echo hi
```

The output is:

```
hi
```

Great, that works. Now I want to use podman-compose to do the same, and execute the command from an existing container in my pod, so I turn this into:

```
podman-compose exec some_container echo "hi"
```

The output is now the expected output, prefixed and suffixed with debug information:

```
['podman', '--version', '']
using podman version: 4.0.3
podman exec --interactive --tty some_container_1 echo hi
hi
exit code: 0
```

This debug information is useful, but is usually redundant in scenarios such as `podman-compose up` (and **also seems to expose secrets** if you pass them through the environment, as it also logs the environment variables it passes), so the best approach seems to lower the verbosity by default.

### PR DESCRIPTION
**Pull request by jamesob**
Fixes #489.

Introduces a `--verbose` flag if you want to see all the noise that was previously printed by default.

### CODE REVIEW

**Comment by errodrigues** [comment]
Any updates on this?

**Comment by alvarolop** [comment]
Hello, any updates on this?

**Comment by maurerle** [comment]
@jamesob can please you rebase onto main to resolve the conflict?

Hopefully this helps to get this merged.

**Comment by jamesob** [comment]
I've stopped using podman because the tooling is too bad, but I'll try to get back to this at some point soon.

**Comment by maurerle** [comment]
So you don't mind if i rebase this and file a new PR?

**Comment by jamesob** [comment]
@maurerle by all means!

**Comment by maurerle** [comment]
This is superseded by #741

**Pull request closed without merging**
