### PR TITLE
Provide support for conditional dependencies

### LINKED ISSUE #866: Fails to handle the `service_healthy` condition of a `depends_on` element
**Describe the bug**
`podman-compose` fails to handle the `service_healthy` condition of a [`depends_on`](https://github.com/compose-spec/compose-spec/blob/master/spec.md#long-syntax-1) element.

**To Reproduce**

1. Create the following `docker-compose.yml` file

```yaml
services:
  base:
    image: docker.io/debian
    command: [ "tail", "-f", "/dev/null" ]
    healthcheck:
      test: [ "CMD", "false" ]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 1m

  dependent:
    image: docker.io/debian
    depends_on:
      base:
        condition: service_healthy
    command: [ "tail", "-f", "/dev/null" ]
```

2. Run `podman-compose -f docker-compose.yml up -d` in the containing directory

**Expected behavior**
The container corresponding to the `dependent` service never starts since the `base` can never be healthy.

**Actual behavior**
The container corresponding to the `dependent` service always starts.

**Output**

```
podman-compose version
podman-compose version: 1.0.6
['podman', '--version', '']
using podman version: 4.3.1
podman-compose version 1.0.6
podman --version 
podman version 4.3.1
exit code: 0
```

**Environment:**
 - OS: Debian GNU/Linux 12 (bookworm)
 - podman version: 4.3.1
 - podman compose version: 1.0.6

### PR DESCRIPTION
**Pull request by flixman**
Currently all services dependencies are treated unconditionally. However, [docker-compose supports](https://docs.docker.com/compose/how-tos/startup-order/#control-startup) specifying three possible conditions (started, healthy, successfully finished). This PR provides such support, also for all podman conditions, extending the existing unit tests for dependencies.

Additionally: statements to retrieve values with defaults from dictionaries have been cleaned up.

Fixes #866

### CODE REVIEW

**Comment by flixman** [comment]
@p12tic I hope you'll find this PR more according to the project standards :-)

**Comment by p12tic** [comment]
> I hope you'll find this PR more according to the project standards :-)

Thanks, way easier to review.

**Comment by p12tic** [comment]
There's a formatting check failing, but I think you've done enough bending to the project requirements, I will finish the rest :-)

**Comment by bkanuka** [comment]
@flixman were you able to test ` condition: service_completed_successfully`? Asking because it looks like you wrote code to handle it in this PR but I can't get it to work, and I don't see a test for it. I wanted to ping you here before I open a bug because you are probably closest to it.

**Comment by aabounegm** [comment]
@bkanuka Did you manage to get it to work? I'm also having problems with `condition: service_completed_successfully`. Specifically, this is the error I'm getting:
```
Error: unable to start container [id1]:
  preparing container [id1] for attach:
    generating dependency graph for container [id1]:
      container [id2] depends on container [id3] not found in input list: no such container
```
I checked, and the required container ran and exited successfully.
 
These are the versions I'm on:
```
podman-compose version 1.5.0
podman version 5.7.1
```

**Comment by bkanuka** [comment]
No I never got it to work. I had to stick with Docker in this case.

**Comment by mokibit** [comment]
The problem with `condition: service_completed_successfully` was fixed by https://github.com/containers/podman-compose/pull/1481.

**Pull request merged**
