### PR TITLE
Restart containers

### PR DESCRIPTION
**Pull request by mellon85**
Properly manage podman container lifetime. Restart containers in case they unexpectedly die.
Doesn't support restarting a container if it was removed (i.e. podman rm -f ID)

### CODE REVIEW

**Comment by muayyad-alsadi** [comment]
Thank you, this seems a lot of work

podman create supports --restart=policy

We might just pass it?

https://github.com/containers/libpod/blob/master/docs/podman-create.1.md

**Comment by mellon85** [comment]
Cool, sure, I'll switch to that, but I would still keep the changes to avoid having threads and use sigchld if that's fine with you

**Comment by muayyad-alsadi** [comment]
I'll review the code in the weekend

**Comment by muayyad-alsadi** [comment]
I've reviewed the code and I liked the idea

http://man7.org/linux/man-pages/man3/atexit.3.html
https://docs.python.org/3/library/atexit.html

but I don't think we can do it.
because it only handles normal exit
for example if a service went out of memory limit (set by `podman run -m 100m` or `mem_limit: 100m` in `docker-compse.yml`) or someone send a signal ...etc.

if you don't like threads, we can use `select.epoll`

https://stackoverflow.com/questions/3194018/wait-the-end-of-subprocesses-with-multiple-parallel-jobs

I'll keep this PR open. and maybe revisit it (after fixing volume mounts)

thank you for your contributions.

**Pull request closed without merging**
