### PR TITLE
feat: generate hosts

### PR DESCRIPTION
**Pull request by muxueqz**

### CODE REVIEW

**Comment by muayyad-alsadi** [comment]
I'm sure this is not needed

when tested with this

https://github.com/containers/podman-compose/tree/devel/tests/nets_test1

```
$ podman_compose.py up -d
$ podman_compose.py exec web1 cat /etc/hosts
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6

10.89.11.2	web1 nets_test1_web1_1
10.89.11.1 host.containers.internal
```

**Comment by muxueqz** [comment]
> I'm sure this is not needed
> 
> when tested with this
> 
> https://github.com/containers/podman-compose/tree/devel/tests/nets_test1
> 
> ```
> $ podman_compose.py up -d
> $ podman_compose.py exec web1 cat /etc/hosts
> 127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
> ::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
> 
> 10.89.11.2	web1 nets_test1_web1_1
> 10.89.11.1 host.containers.internal
> ```

but web1 can't resolve web2 by the hosts,
I want to web1 can resolve web2, web2 can resolve web1

**Comment by muayyad-alsadi** [comment]
you have uninstalled dependency.
quote from the readme

```
[podman dnsname plugin](https://github.com/containers/dnsname): It is usually found in the podman-plugins or podman-dnsname distro packages, those packages are not pulled by default and you need to install them. This allow containers be able to resolve each other if they are on the same CNI network.
```

**Comment by muxueqz** [comment]
> you have uninstalled dependency. quote from the readme
> 
> > [podman dnsname plugin](https://github.com/containers/dnsname): It is usually found in the podman-plugins or podman-dnsname distro packages, those packages are not pulled by default and you need to install them. This allow containers be able to resolve each other if they are on the same CNI network.

emmm. I don't want to install dnsname plugin and dnsmasq

**Comment by muayyad-alsadi** [comment]
any reasoning for that?

NOTE: separation of concern, if podman can do it, then let podman do it.

**Pull request closed without merging**
