### PR TITLE
Allow config to merge strings and lists in "command" and "entrypoint"

### PR DESCRIPTION
**Pull request by Evedel**
There is an inconsistency in which types are allowed to be merged where. While the `docker compose` allows (only) strings and lists to be merged for both `entrypoint` and `command`, `podman compose` only allows that for `command`. Entrypoint is also not merged but extended when it is `list` in both configs.

Merge `str` & `str` without spaces:
Change: none
image

Merge `str` & `str` with spaces:
Change: result is split into a list of strings
image

Merge `list` and `list`:
Change: fixes incorrect extension
image

Merge `str` and `list`:
Change: allows merge
image

Not a `str` or a `list` of `str` in any position:
Change: more verbose output
image

### CODE REVIEW

**Comment by Evedel** [comment]
going to resolve #622

**Comment by muayyad-alsadi** [comment]
Should we just replace split with shlex.split?

**Comment by Evedel** [comment]
Very good point! Huge thanks for pointing that out @muayyad-alsadi, I've added a bunch of test cases including one covering a particular scenario where `shlex` will be most critical.

**Comment by Evedel** [comment]
redone this PR in the spirit of #685

**Pull request merged**
