### PR TITLE
Add necessary commands for VSCode Devcontainers

### PR DESCRIPTION
**Pull request by howlowck**
Changes:
* Added `short` and `format` args to `version` command
* Added a trivial implementation of the `config` command which echos out the content when given an absolute path of a file

Resolves:
* microsoft/vscode-remote-release#5553
* #106

### CODE REVIEW

**Comment by muayyad-alsadi** [comment]
does vscode expects
version on stdout or stderr?

the following line should be replaced with `log(...)` (it just a helper that just print to stderr)

```
        sys.stderr("File path is required. use -f flag to set the input file")
...
    if (file_path == None):
        sys.stderr("File path is required. use -f flag to set the input file")
        return
```

even more, this should be part of parsing, which is handled by `argparse` not need at all to process it

```
parser.add_argument("-f", "--format", type=str, default='pretty', 
        help="Format the output. Values: [pretty | json].")
```

should have choices like this

```
parser.add_argument("-f", "--format", choices=['pretty', 'json'], default='pretty'
                            help="Format the output")
```

please don't construct json by substitution and concatenation and replace, use `json.dumps`

```
        print('{ "version": "{version}" }'.replace('{version}', __version__))
```

should be

```
        res = {"version": __version__}
        print(json.dumps(res))
```

**Comment by howlowck** [comment]
Hey @muayyad-alsadi, thanks for the quick review. vscode expects stdout. I will make the suggested updates.

**Comment by howlowck** [comment]
Updated. Thanks again!

**Comment by muayyad-alsadi** [comment]
I'll do some changes and need your help testing them.

**Comment by muayyad-alsadi** [comment]
I've made config prints the merged yaml of multiple files
please test

**Comment by howlowck** [comment]
Yes. Multiple files are merging properly.

**Pull request merged**
