### PR TITLE
Add ability to input docker-compose.yaml via stdin

### PR DESCRIPTION
**Pull request by ArthoPacini**
Simple modification to add the ability to input docker-compose.yaml via stdin, that was lacking...

### CODE REVIEW

**Comment by ArthoPacini** [comment]
That would solve https://github.com/containers/podman-compose/issues/269#issue-793229346

**Comment by p12tic** [comment]
Looks good, thanks. Could you also document this enhancement here? https://github.com/containers/podman-compose/blob/main/podman_compose.py#L2051 (e.g. `When file is "-", standard input is read` or anything better you can think of.

**Comment by ArthoPacini** [comment]
The final help message is "Specify an compose file (default: docker-compose.yml) or '-' to read from stdin."

It seems that the static check didn't allowed larger messages.

**Comment by p12tic** [comment]
> It seems that the static check didn't allowed larger messages.

I think it would have allowed a string broken across multiple lines. Anyway, current message is enough.

**Comment by ArthoPacini** [comment]
It seems that on the `resolve_extends` function it also reads the docker-compose.yaml file using the `yaml.safe_load()` function. I don't know exactly what this function is doing, it seems to be called somewhere on the `_parse_compose_file()` function, so it might be wise to check that out and see if it needs the same kind of modification. For now, it works great I can pass docker-compose.yaml files via stdin. Keep up the good work!

**Pull request merged**
