### PR TITLE
Add support of exec

### PR DESCRIPTION
**Pull request by leroyguillaume**
Add support of exec.

### CODE REVIEW

**Comment by muayyad-alsadi** [comment]
I'm using `subparsers.add_parser(...)` not `parser.parse_known_args(...)`

```
@cmd_parse(podman_compose, ['exec'])
def compose_exec_parse(parser):
    parser.add_argument("-i", "--interactive", action='store_true', help="Keep STDIN open even if not attached.")
    parser.add_argument("-t", "--tty", action='store_true', help="Allocate a pseudo-TTY. The default is false.")
    parser.add_argument('service', metavar='service', nargs=None, help='service name')
    parser.add_argument('exec_command', metavar='exec_command', nargs=None, help='command to execute')
    parser.add_argument('exec_args', metavar='exec_args', nargs='*',default=None,
                        help='args to pass to command')
```

but I'm not sure if this would work when exec_args have something like '--help'

```
podman-compose exec mybusybox httpd -f -p 8080
```

**Comment by hissssst** [comment]
Any info when this will be merged in? What is blocking this PR?

**Comment by dwt** [comment]
@muayyad-alsadi is this obsolete since #292 was merged? Is there stuff in here that should be salvaged?

**Comment by abitrolly** [comment]
@dwt as an author of alternative `exec` implementation you probably know better.

**Comment by dwt** [comment]
Sorry, I have only looked at the code of this pull request quite superficially, so…

**Comment by abitrolly** [comment]
@dwt yes, but if you have the time to review this, that will help maintainers to check and decide what to do. Will help greatly. )

**Comment by muayyad-alsadi** [comment]
I'll close this because it's included in #292

**Pull request closed without merging**
