### PR TITLE
Allow config to merge strings and dicts in "build"

### PR DESCRIPTION
**Pull request by Evedel**
Context:
Trying to make `podman-compose` to work with vscode devcontainers.

vscode will take provided compose files, extend them, create it own extentions, merge them through `podman-compose config` and run. vscode will also create a dockerfile with a new name and place it in the temporary directory. However the merge of `build` section is not currently handled correctly.

The simplified problem is:
compose-1:
```
services:
  dev:
    build: ./dir-1
```

compose-2:
```
services:
  dev:
    build:
      context: ./dir-2
```

expected output
```
services:
  dev:
    build:
      context: ./dir-2
```

actual output
```
    raise ValueError(
ValueError: can't merge value of build of type <class 'str'> and <class 'dict'>
```

### CODE REVIEW

**Comment by Evedel** [comment]
Going to resolve #612, and build a base for resolving #620 and #300

**Comment by muayyad-alsadi** [comment]
`normalize` (which calls `normalize_service`) is called just before `rec_merge`

the current code looks like

```
def normalize_service(service, sub_dir=""):
    # make `build.context` relative to sub_dir
    # TODO: should we make volume and secret relative too?
    if sub_dir and "build" in service:
        build = service["build"]
        context = build if is_str(build) else build.get("context", None)
# ..........
            if is_str(build):
                service["build"] = context
            else:
                service["build"]["context"] = context
```

I believe we can just move normalize build as part of this by moving the last part at top
like this

```
def normalize_service(service, sub_dir=""):
    if "build" in service:
        build = service["build"]
        if is_str(build):
            service["build"] = {"context": build}
    # below this line build will always be dict, code should be simpler
    # make `build.context` relative to sub_dir
    # TODO: should we make volume and secret relative too?
    if sub_dir and "build" in service:
        build = service["build"]
        context = build if is_str(build) else build.get("context", None)
# ..........
```

**Comment by Evedel** [comment]
Good call, thanks, that is done.

**Comment by muayyad-alsadi** [comment]
Please resolve the conflict

**Comment by Evedel** [comment]
resolved

**Comment by muayyad-alsadi** [comment]
I still see conflict

**Comment by Evedel** [comment]
Could you please doublecheck? Not sure if that was/is a glitch in GH GUI, cannot see any merge warnings...

**Comment by muayyad-alsadi** [comment]
sorry for being late, it merged fine

> Not sure if that was/is a glitch in GH GUI

indeed that could be the case

**Pull request merged**
