### PR TITLE
bring colors into container logging from unmerged pr #192

### PR DESCRIPTION
**Pull request by chutchi2**
Signed-off-by: Cody Hutchins <codyhutchins@seed-innovations.com>

### CODE REVIEW

**Comment by chutchi2** [comment]
Created PR because #192 appears to have achieved this feature perfectly but was never merged. I believe it is a simple addition and of use to any users both familiar with docker-compose behavior and not.

**Comment by bluflowr** [comment]
This would definitely add value. Looks good.

**Comment by muayyad-alsadi** [comment]
I've tested it with
https://github.com/containers/podman-compose/blob/devel/tests/testlogs/docker-compose.yml

and it seems working fine

**Comment by josejsarmento** [comment]
Any ETA for when this will be merged into stable branch?

**Pull request merged**
