### PR TITLE
Devel

### PR DESCRIPTION
**Pull request by barseghyanartur**
Tiny fix.

### CODE REVIEW

**Comment by muayyad-alsadi** [comment]
I like having extra comma for multi line args or lists or dicts

```
A=[
  1,
  2,
  3,
]
```

Sorry

**Comment by barseghyanartur** [comment]
@muayyad-alsadi:

That comma is causing errors on Python 2.

**Comment by muayyad-alsadi** [comment]
Python 2 is reaching EOL in 2020

**Comment by barseghyanartur** [comment]
@muayyad-alsadi:

No problem at all. When I was proposing the fix, I was considering current state of the code at time and as far as I could see it was (and still is written) with Python 2 in mind.

This:

```python
from __future__ import print_function
```

Or this:

```python
PY3 = sys.version_info[0] == 3
if PY3:
    basestring = str
```

These are Python 2 artifacts.

Would you rather accept (and interested in) a Python 2 clean-up pull request?

**Pull request closed without merging**
