### PR TITLE
Support additional_contexts

### LINKED ISSUE #762: Support `additional_contexts`
**Is your feature request related to a problem? Please describe.**
I have a project that is split to multiple sub-projects that share a common set of data.
Each sub-project includes a `docker-compose.yml` for setting things up.
To include the shared data, I would like to do this in `docker-compose.yml`:

```
services:
  myservice:
    build:
      context: .
      additional_contexts:
        data: ../data
```

And then in `Dockerfile` for `myservice`:

```
COPY --from=data somedata.json /data/somedata.json
```

But, when I run `podman-compose`, I see this:

```
[4/4] STEP 4/8: COPY --from=data somedata.json /data/somedata.json
? Please select an image: 
  ▸ registry.fedoraproject.org/data:latest
    registry.access.redhat.com/data:latest
    docker.io/library/data:latest
    quay.io/data:latest
```

**Describe the solution you'd like**
Implement [additional_contexts] from the Compose Specification.

[additional_contexts]: https://github.com/compose-spec/compose-spec/blob/master/build.md#additional_contexts

**Describe alternatives you've considered**
1. Use Docker Compose instead, which [implements that feature](https://github.com/docker/compose/pull/10369).
1. Restructure my project so that each subproject contains a copy of the data directory,
or copy the data to sub-projects folder in a preparatory build step.
This would work, but requires restructuring the project even though `additional_contexts` is part of the Compose Specification.

**Additional context**
Yes, please! 😁

### PR DESCRIPTION
**Pull request by otto-liljalaakso-nt**
Fixes #762

### CODE REVIEW

**Comment by theyoyojo** [comment]
👍 I'm using this commit in my fork

**Review by p12tic — CHANGES_REQUESTED** [review]
Thanks for the PR, looks great!

Could you add unit tests (pytests/ directory) and also an automatic runner for the docker-compose.yml that you've added. There are examples of such tests in tests directory now.

**Comment by otto-liljalaakso-nt** [comment]
I have added the automatic runner test in `tests/`. I also tried looking at unit tests, but I would need some guidance here.

This PR touches two functions: `normalize_service()` and `build_one()`.

`normalize_service()` is called by some unit tests, but not in systematic fashion: The test files are called `test_can_merge_build.py`, which is about `build` key specifically, and `test_can_merge_cmd_ent.py`, which I do not really understand, but apparently is about command line arguments.

My question 1: Should I create a new file `test_can_merge_additional_contexts.py` and write my unit tests there, or what is the expectation here?

`build_one()` is not called by any unit test, and is a bit problematic for unit testing because it does filesystem access.

My question 2: Is the expectation that I should develop enough unit testing framework, with filesystem mocking etc., for `build_one()`, so I can unit test the changes in this pull request? I can create something, I am just not sure if assigning such task to first time, drive-by contributor is a good idea.

**Comment by tchernobog** [comment]
Hi @p12tic , we were also looking for this feature to be implemented, and it seems like @otto-liljalaakso-nt addressed partially your review comments.

Could you answer his question and move this forward?

**Comment by p12tic** [comment]
I'm sorry, I missed the comment by @otto-liljalaakso-nt.

> normalize_service() is called by some unit tests, but not in systematic fashion: The test files are called test_can_merge_build.py, which is about build key specifically, and test_can_merge_cmd_ent.py, which I do not really understand, but apparently is about command line arguments.

I cleaned up `normalize_service()` tests. They are now in pytests/test_normalize_service.py. Indeed the tests were hard to understand, hopefully no more.

> My question 1: Should I create a new file test_can_merge_additional_contexts.py and write my unit tests there, or what is the expectation here?

As of now the best place for normalize_service tests is in pytests/test_normalize_service.py.

> build_one() is not called by any unit test, and is a bit problematic for unit testing because it does filesystem access.

Agreed. But I think the change is simple enough that we can leave it untested. I feel that the amount of effort needed to test build_one() is too high for the benefits.

> My question 2: Is the expectation that I should develop enough unit testing framework, with filesystem mocking etc., for build_one(), so I can unit test the changes in this pull request? I can create something, I am just not sure if assigning such task to first time, drive-by contributor is a good idea.

Completely agreed. Lack of testing framework is problem of the project. Until there's one, the parts that are hard to test will unfortunately be untested.

**Comment by otto-liljalaakso-nt** [comment]
@p12tic I have updated `tests/normalize_service.py` to test this change. CI is showing red, as did `pre-commit` which instructed by `CONTRIBUTING.md`. According to my analysis, none of the reported problems are caused by changes in this PR:

1. Black wants to reformat some files. Some of those are not changed in this PR. `tests/normalize_service.py` is changed in this PR, but the changed Black wants to apply are much wider than that. So I think those problems should not be fixed in this PR.
2. Test case `test_podman_compose_include` fails, but it also fails on `master` branch, so I do not think the problem should be fixed in this PR.

**Comment by otto-liljalaakso-nt** [comment]
If you prefer, I can add a commit that runs Black and applies the changes it wants to make. For the failing test case, I don't know what it is about.

**Review by p12tic — APPROVED** [review]
Thanks, everything looks good.

**Comment by p12tic** [comment]
> If you prefer, I can add a commit that runs Black and applies the changes it wants to make. 

I ran `ruff format .` after rebasing, no need to do anything. Thanks!

**Comment by otto-liljalaakso-nt** [comment]
> > If you prefer, I can add a commit that runs Black and applies the changes it wants to make.
> 
> I ran `ruff format .` after rebasing, no need to do anything. Thanks!

Great to hear that.

I would like to suggest reviewing [pre-commit configuration](https://github.com/containers/podman-compose/blob/main/.pre-commit-config.yaml) and the suggestion to run that in CONTRIBUTING.md. It looks like pre-commit and CI are using different tools for the same purpose, leading to confusion like this.

**Pull request merged**
