### PR TITLE
little improvement

### PR DESCRIPTION
**Pull request by sycured**
Some simplification and refacto about import (optimization) which can help about speed and memory usage

### CODE REVIEW

**Comment by muayyad-alsadi** [comment]
as far as I know, python will evaluate the entire module even if you just import a single function

for example


```python
# mymodule.py

def myfunc(): pass

print("foo")
```

if you type `from mymodule import myfunc` then `foo` will be printed despite being outside the myfunc.

can you please cite some official documentation that support your claim.
otherwise keeping the module as namespace if cleaner.

**Comment by diefans** [comment]
the lookup is indeed faster if you directly import module attributes, but at the cost of maintenance.
```
❯ ipython
Python 3.7.4 (default, Apr 16 2020, 14:04:07)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.8.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import os

In [2]: from os import path

In [3]: def foo():
   ...:     x = os.path
   ...:

In [4]: def bar():
   ...:     x = path
   ...:

In [5]: import dis

In [6]: dis.dis(foo)
  2           0 LOAD_GLOBAL              0 (os)
              2 LOAD_ATTR                1 (path)
              4 STORE_FAST               0 (x)
              6 LOAD_CONST               0 (None)
              8 RETURN_VALUE

In [7]: dis.dis(bar)
  2           0 LOAD_GLOBAL              0 (path)
              2 STORE_FAST               0 (x)
              4 LOAD_CONST               0 (None)
              6 RETURN_VALUE
```

**Comment by sycured** [comment]
@muayyad-alsadi The support of my claim is already did by @diefans … Thanks a lot @diefans to be more quick

@diefans, my ide knows that `path` is from `os` and I see it so, this depend of each developer…
It's possible to do (an example): `from os import path as os_path`

**Comment by diefans** [comment]
@sycured IMHO the module import makes more sense:
- less noise
- clear namespaces when reading code
- easy use of additional attributes without a new import statement
- clear and consistent mocking

Code is read a lot more than it is written and not everybody has a fancy IDE at hand/terminal/browser

**Comment by sycured** [comment]
Sorry to use an ide that understand optimization (pycharm/vscode/theia).

So I'll have the same return about the cognitive complexity of container_to_args… 58 which it's high and also SonarQube is telling me that thing, not just flake8 with my settings : https://sonarcloud.io/project/issues?id=sycured_podman-compose&open=AXLIE3KE1HlXjxKTbGm-&resolved=false&types=CODE_SMELL

**Comment by diefans** [comment]
@sycured complexity is not caused by import names or attribute lookup, but by the amount of code paths. 
In the case of `container_to_args` I would use a data class e.g. https://www.attrs.org/en/stable/ for representation and use https://github.com/Tinche/cattrs to unstructure it into a command line - that would save you over 100 lines of code. This would for sure introduce the right shape of maintainable code.

**Comment by sycured** [comment]
@diefans I know but for me it's the same fight: optimization

I won't start a war about coding style, I prefer to reserve it to a blog post…

If you prefer to close this PR, you can do it… Now, I know your philosophy about secure coding… Because letting access to all sys or os when you just need one thing it isn't a good practice about less privilege or access.

**Comment by diefans** [comment]
@sycured in python there is no such thing like "secure coding" or "a private or protected something" and also no philosophy about those concepts.

Honestly I don't get your point about "privilege", "access" and "good practice".

But a benefit of using module imports is to just have it at hand without introducing another import. Also mocking is not so confusing, since you mock always the source module and not the imported name of your module in question.

IMO your PR is just introducing a lot more names without improving anything. But anyways - I am only interested in this project and how it evolves, that's why I commented.

**Pull request closed without merging**
