### PR TITLE
Support extends

### PR DESCRIPTION
**Pull request by mariushoch**
https://docs.docker.com/compose/extends/

Doesn't yet support referring to another file.

Needs Python 3.5+ (for merging dicts using **)

### CODE REVIEW

**Comment by mariushoch** [comment]
This is somewhat WIP still :/

**Comment by muayyad-alsadi** [comment]
please don't check for docker-compose file version. 
just implement the feature.

BTW: we already support two ways of extending

1. via passing multiple files (by default "docker-compose.override.yml"), for example with -f 1.yml 2.yml

2. via yaml magic like [tests/tamlmagic](https://github.com/containers/podman-compose/blob/devel/tests/yamlmagic/docker-compose.yml)

**Comment by mariushoch** [comment]
> please don't check for docker-compose file version. just implement the feature.

Good idea, no need to be strict here. Removed.
> BTW: we already support two ways of extending

Hm, I don't think these fit the needed semantics close enough.

**Comment by muayyad-alsadi** [comment]
I'm considering using:

```
def rec_merge(target, source):
```

https://github.com/containers/podman-compose/blob/dee813a4b6f0f06131f021147ae09cef3eb5c875/podman_compose.py#L644

**Comment by mariushoch** [comment]
> I'm considering using:
> 
> ```
> def rec_merge(target, source):
> ```
> 
> https://github.com/containers/podman-compose/blob/dee813a4b6f0f06131f021147ae09cef3eb5c875/podman_compose.py#L644

How would that look? I'm fairly sure that's not going to be enough for my use cases :/

**Comment by muayyad-alsadi** [comment]
I'll handle it.

**Comment by muayyad-alsadi** [comment]
files are not supported

https://github.com/containers/podman-compose/commit/9e0dd2da9d70731cf2068d62b495f6e2883e8870

**Pull request merged**
