### PR TITLE
Add `--network=none` if `network_mode: none` is set

### LINKED ISSUE #1001: `network_mode: none` is ignored
**Description of the bug**

If a service uses `network_mode: none` the value `none` is accepted, but it does not change the arguments passed to podman.

**To Reproduce**
The following compose file can be used to reproduce:

`compose-test.yml`:
```
services:
  test:
    image: "busybox"
    network_mode: "none"
    command: "ip addr show"
```

**Expected behavior**
Passing `--network=none` to `podman run`.

**Actual behavior**
No `--network=none` is passed to `podman run`.

**Output**

```
$ ${HOME}/.local/bin/podman-compose version
podman-compose version 1.2.0
podman version 4.3.1

$ ${HOME}/.local/bin/podman-compose --verbose -f compose-test.yml up
INFO:podman_compose:['podman', '--version', '']
INFO:podman_compose:using podman version: 4.3.1
DEBUG:podman_compose:** excluding: set()
INFO:podman_compose:['podman', 'ps', '--filter', 'label=io.podman.compose.project=tmp', '-a', '--format', '{{ index .Labels "io.podman.compose.config-hash"}}']
INFO:podman_compose:podman pod create --name=pod_tmp --infra=false --share=
b9b001c1b1bafcaed3937dcc6cc5e0532aa97826a00873c553fa909e5da61e1a
INFO:podman_compose:exit code: 0
INFO:podman_compose:podman create --name=tmp_test_1 --pod=pod_tmp --label io.podman.compose.config-hash=322299545b4b3d15d0760e70b68f4cae2c66a1247dadd66cb486d1aa6f0e122c --label io.podman.compose.project=tmp --label io.podman.compose.version=1.2.0 --label PODMAN_SYSTEMD_UNIT=podman-compose@tmp.service --label com.docker.compose.project=tmp --label com.docker.compose.project.working_dir=/home/bg/tmp --label com.docker.compose.project.config_files=compose-test.yml --label com.docker.compose.container-number=1 --label com.docker.compose.service=test busybox ip addr show
9004c9e9ebc54a654aafc31a9e1a7dd57296a3328c11832f261717a23c84c5f2
INFO:podman_compose:exit code: 0
INFO:podman_compose:podman start -a tmp_test_1
[test] | 1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue qlen 1000
[test] |     link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
[test] |     inet 127.0.0.1/8 scope host lo
[test] |        valid_lft forever preferred_lft forever
[test] |     inet6 ::1/128 scope host 
[test] |        valid_lft forever preferred_lft forever
[test] | 2: tap0: <BROADCAST,UP,LOWER_UP> mtu 65520 qdisc fq_codel qlen 1000
[test] |     link/ether 12:e7:a1:86:e5:24 brd ff:ff:ff:ff:ff:ff
[test] |     inet 10.0.2.100/24 brd 10.0.2.255 scope global tap0
[test] |        valid_lft forever preferred_lft forever
[test] |     inet6 fd00::10e7:a1ff:fe86:e524/64 scope global dynamic flags 100 
[test] |        valid_lft 86400sec preferred_lft 14400sec
[test] |     inet6 fe80::10e7:a1ff:fe86:e524/64 scope link 
[test] |        valid_lft forever preferred_lft forever
INFO:podman_compose:exit code: 0
```

**Additional context**
The error seems to be a missing statement in `get_net_args()`. I will submit a pull request in a few minutes.

### PR DESCRIPTION
**Pull request by nerilex**
This PR is response / fix for #1001.

### CODE REVIEW

**Comment by p12tic** [comment]
See e.g. https://github.com/containers/podman-compose/pull/1000/commits/85050097e51ecaf1c02db1957d9c25815188668c

**Comment by nerilex** [comment]
Thanks for reminding me :).

**Review by p12tic — APPROVED** [review]

**Comment by p12tic** [comment]
Rebased and squashed the commits into one. Test changes should come together with the feature in the same commit

**Comment by p12tic** [comment]
Added newsfragment.

**Pull request merged**
