### PR TITLE
Fix `up` arguments parsing

### PR DESCRIPTION
**Pull request by abitrolly**
These is already parsed here.

https://github.com/containers/podman-compose/blob/502d7cc206da1f20cc9aef480f93f6b32d576f80/podman_compose.py#L1644

### CODE REVIEW

**Comment by ret2libc** [comment]
I was going to submit exactly this. Awesome! Unfortunately specifying services is not implemented anyway :(

**Comment by abitrolly** [comment]
Yep. But at least now it is obvious.

**Review by StevenDias33 — APPROVED** [review]

**Comment by muayyad-alsadi** [comment]
> Unfortunately specifying services is not implemented anyway :(

it's implemented now
please help me test

**Comment by abitrolly** [comment]
@muayyad-alsadi `podman-compose up <service>` works for me. Thanks.

**Pull request merged**
