### PR TITLE
Stop other containers when --abort-on-container-exit is used

### PR DESCRIPTION
**Pull request by jaikiran**
`podman-compose up`, like `docker-compose` provides a `--abort-on-container-exit` option to stop the containers that were launched by the `up` command when any of the other containers exit. In its current form in the `devel` branch, this isn't functional and the other containers keep running. This is also reported as an issue here https://github.com/containers/podman-compose/issues/679.

The commit in this PR adds this missing behaviour. I've tested this against one of the projects that I am using `podman-compose` in. Plus, I've also verified the trivial example that the reporter in https://github.com/containers/podman-compose/issues/679 provided and it now stops the rest of the containers.

### CODE REVIEW

**Comment by jaikiran** [comment]
Any thoughts about this change?

**Comment by muayyad-alsadi** [comment]
I'm considering moving to python3's builtin asyncio and drop all threads if possible.

I need some time to look into this change.

**Comment by jaikiran** [comment]
Thank you @muayyad-alsadi. Please take your time. Looking forward to your changes and will test them out with our project when they are ready.

**Comment by hcd3** [comment]
Hi @jaikiran and @muayyad-alsadi. Thank you for working on this feature!

Is there any update on this issue? I've run into the error which pertains to this MR and Podman support for the `--abort-on-container-exit` option would be greatly beneficial.

**Comment by Falmarri** [comment]
@muayyad-alsadi I have an PR for moving to asyncio that fixes this issue as well https://github.com/containers/podman-compose/pull/810

**Comment by jaikiran** [comment]
Closing, now that the asyncio approach has been merged.

**Pull request closed without merging**
