### PR TITLE
Remove named volumes during "down -v"

### LINKED ISSUE #105: Remove all volumes when shutting down
`docker-compose` offers to possibility to remove all volumes used by your services by appending the `-v` option to the `down` command. It is very useful to me in my daily work and unfortunately it seems to be missing in `podman-compose`.

Is there a good reason why this option should not be added? Otherwise, I would simply add it myself and open a PR 👍

### PR DESCRIPTION
**Pull request by lcarva**
Fixes #105

Signed-off-by: Luiz Carvalho <lucarval@redhat.com>

### CODE REVIEW

**Comment by lcarva** [comment]
@muayyad-alsadi any chance you could have a look on this one? Thanks in advance!

**Comment by muayyad-alsadi** [comment]
I'm very sorry for taking so long. I've moved to a new house and I feel I must review this one because I don't want to remove volumes by mistake.

BTW we can remove volumes using labels.

**Comment by lcarva** [comment]
> I'm very sorry for taking so long. I've moved to a new house and I feel I must review this one because I don't want to remove volumes by mistake.
> 
> BTW we can remove volumes using labels.

No worries! I hope the new house is wonderful.

I've tried to use a single podman command to remove all the volumes based on labels, but was not able to do so. I've opted to listing all the volumes and inspecting the labels on each one. I'm happy to hear an alternative approach.

**Comment by muayyad-alsadi** [comment]
> No worries! I hope the new house is wonderful.

in deed, it's a nice villa.

> I've tried to use a single podman command to remove all the volumes based on labels,

we set a label `io.podman.compose.project` with value equal to project name
the single command is

```
podman volume list --format '{{.Name}}' -f 'label=io.podman.compose.project=HERE' | xargs -r podman volume rm
```

I had the following todo comment in the source code

```
    # TODO: might move to using "volume list"
    # podman volume list --format '{{.Name}}\t{{.MountPoint}}' -f 'label=io.podman.compose.project=HERE'
    try: out = compose.podman.output(["volume", "inspect", vol_name]).decode('utf-8')
    except subprocess.CalledProcessError:
        compose.podman.output(["volume", "create", "--label", "io.podman.compose.project={}".format(proj_name), vol_name])
        out = compose.podman.output(["volume", "inspect", vol_name]).decode('utf-8')
```

**Comment by lcarva** [comment]
> > No worries! I hope the new house is wonderful.
> 
> in deed, it's a nice villa.
> 
> > I've tried to use a single podman command to remove all the volumes based on labels,
> 
> we set a label `io.podman.compose.project` with value equal to project name
> the single command is
> 
> ```
> podman volume list --format '{{.Name}}' -f 'label=io.podman.compose.project=HERE' | xargs -r podman volume rm
> ```
> 
> I had the following todo comment in the source code
> 
> ```
>     # TODO: might move to using "volume list"
>     # podman volume list --format '{{.Name}}\t{{.MountPoint}}' -f 'label=io.podman.compose.project=HERE'
>     try: out = compose.podman.output(["volume", "inspect", vol_name]).decode('utf-8')
>     except subprocess.CalledProcessError:
>         compose.podman.output(["volume", "create", "--label", "io.podman.compose.project={}".format(proj_name), vol_name])
>         out = compose.podman.output(["volume", "inspect", vol_name]).decode('utf-8')
> ```

Yes, I saw that. That syntax doesn't work for me with podman 2.1.1.

**Comment by markandrewj** [comment]
Any word on this? I notice the discussion around it stopped in 2020.

**Comment by sferich888** [comment]
@lcarva  can we fix the merge conflicts?

**Comment by lcarva** [comment]
> @lcarva can we fix the merge conflicts?

Done!

**Comment by muayyad-alsadi** [comment]
I'll invite you to jump to 1.x branch and start playing with it. I'll port this fix to it.

0.1 for legacy versions of podman, 1.x for modern versions (CNI network, no need for mapping and workarounds).

by the end of this weekend I hope I can update the documentation.

**Comment by muayyad-alsadi** [comment]
@lcarva why you used 

```
podman volume inspect --all
```

instead of 

```
podman volume ls --noheading -f label=io.podman.compose.project=simple --format '{{.Name}}'
```

what are the podman versions that don't support the latter?

**Comment by lcarva** [comment]
> @lcarva why you used
> 
> ```
> podman volume inspect --all
> ```
> 
> instead of
> 
> ```
> podman volume ls --noheading -f label=io.podman.compose.project=simple --format '{{.Name}}'
> ```
> 
> what are the podman versions that don't support the latter?

Podman 2.1.1 is what I had used, but that was over a year ago.

The `-f` filtering was just not working at all. IIRC, it was not checking the value of the label, just its name. It would return any volume that had the label `io.podman.compose.project` regardless of its value.

I just tried this again with Podman 3.4.4 and it appears to have been fixed. I've dug through the podman issues but am unable to find the culprit :(

+1 to switching to using that now, but it may not work for older versions of podman.

**Comment by lcarva** [comment]
> +1 to switching to using that now, but it may not work for older versions of podman.

PR submitted: https://github.com/containers/podman-compose/pull/402

**Comment by muayyad-alsadi** [comment]
podman-compose version 1.x is for podman>=3.1.0
we are safe to go.

**Pull request merged**
